github_analytics:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: idlkunk-ax51793
      user: AARIAS04
      password: MinisterArias04
      role: ACCOUNTADMIN
      database: GITHUB_DATA
      warehouse: COMPUTE_WH
      schema: SILVER
      threads: 4
      client_session_keep_alive: True